Create table employees (
    id bigint generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    middle_name varchar(100),
    email varchar(100) unique not null
);  